apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: harbor-repo.vmware.com/livewell/gateway
        ports:
        - containerPort: 8080
