apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      app: patient
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: patient
    spec:
      containers:
      - name: patient
        image: harbor-repo.vmware.com/livewell/patient
        ports:
        - containerPort: 8089
