apiVersion: v1
kind: Service
metadata:
  name: livewell-gateway-service
  namespace: development
spec:
  selector:
    app: gateway
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
